"""Added task api_keys field

Revision ID: 066e4cdd0abb
Revises: 15ed0767eccd
Create Date: 2025-02-24 13:06:24.197740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066e4cdd0abb'
down_revision: Union[str, None] = '15ed0767eccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('api_keys', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'api_keys')
    # ### end Alembic commands ###
