"""Added queue user_id field

Revision ID: 15ed0767eccd
Revises: 3d23b8308342
Create Date: 2025-02-02 22:24:36.067211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ed0767eccd'
down_revision: Union[str, None] = '3d23b8308342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'user_id')
    # ### end Alembic commands ###
