"""Added proxy table

Revision ID: 3d23b8308342
Revises: cbbbab9cf281
Create Date: 2024-06-04 13:27:26.102136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d23b8308342'
down_revision: Union[str, None] = 'cbbbab9cf281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=37), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('owner', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxy')
    # ### end Alembic commands ###
