"""tasks, queue tables structure update

Revision ID: 6166cc903ac8
Revises: e436fd0447c8
Create Date: 2024-04-14 23:59:26.467147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6166cc903ac8'
down_revision: Union[str, None] = 'e436fd0447c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'owner',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tasks', 'owner',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tasks', 'data',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'data',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('tasks', 'owner',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('queue', 'owner',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
