"""Queue task_id nullable

Revision ID: 7952620b532b
Revises: ad5af088ede0
Create Date: 2026-04-28 12:28:16.939128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7952620b532b'
down_revision: Union[str, None] = 'ad5af088ede0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'task_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'task_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
