"""Added headers field

Revision ID: ad5af088ede0
Revises: 066e4cdd0abb
Create Date: 2025-05-13 17:28:49.693819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5af088ede0'
down_revision: Union[str, None] = '066e4cdd0abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('headers', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'headers')
    # ### end Alembic commands ###
