"""create queue, tasks tables

Revision ID: bd4f18490757
Revises: 
Create Date: 2024-02-20 14:04:29.289185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4f18490757'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('data', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=37), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    op.drop_table('tasks')
    # ### end Alembic commands ###
